version: '3'
services:
  api:
    build:
      context: ./producto  # Ajusta el contexto según la estructura de tu proyecto
      dockerfile: Dockerfile
    container_name: producto_service
    depends_on:
      - db  # Cambia 'db' por el nombre del contenedor o servicio
    networks:
      - red1  # Usa el nombre correcto de la red
    ports:
      - "5003:5003"

networks:
    red1:
    external: true