services:
  api:
    build:
      context: . # Ajusta el contexto según tu proyecto
    container_name: producto_service
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ecomercedb-servidor
      POSTGRES_PORT: 5432
    env_file:
      - ../../../.env  

    networks:
      - red1
    ports:
      - "5003:5000"

networks:
  red1:
    external: true