services:
  api:
    build:
      context: . # Ajusta el contexto según tu proyecto
    container_name: producto_service
    networks:
      - red1
    ports:
      - "5003:5000"

networks:
  red1:
    external: true