services:
  db:
    image: postgres:15.6
    container_name: ecomercedb-servidor
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ecomercedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - red1

volumes:
  postgres_data:

networks:
  red1:
