services:
  api:
    build:
      context: . # Ajusta el contexto según tu proyecto
    container_name: compra_service
    networks:
      - red1
    ports:
      - "5002:5000"

networks:
  red1:
    external: true
