services:
  ms-compras:
    build:
      context: . # Ajusta el contexto según tu proyecto
    container_name: compra_service
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=ecomercedb-servidor
      - POSTGRES_PORT=5432
    env_file:
      - ../../../.env  

    ports:
      - "5002:5000"

networks:
  red1:
    external: true

