version: '3'
services:
  api:
    build:
      context: ./pago  # Cambia esto según tu estructura
      dockerfile: Dockerfile
    container_name: pago_service
    depends_on:
      - db  
    networks:
      - red1
    ports:
      - "5001:5001"  

networks:
    red1:
    external: true  
